name: Manual Deploy to Vercel

on:
  push:
    branches:
      - dev
jobs:
  deploy_production:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev' # Adjust branch if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Manual Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-project-name: "wewantwaste-skip-select"
          scope: ${{ github.repository_owner }}
          prod: true